import type { Metadata } from "next"
import type { ReactNode } from "react"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body>
      {children}
    </body>
  </html>
)

export default RootLayout
