openapi: 3.1.0
x-stoplight:
  id: 2is4sg4de04re
info:
  title: client-backend
  version: '1.0'
  description: for client backend
  contact:
    name: contact
    url: 'https://github.com/akky-xxxx/template-nextjs-monorepo'
servers:
  - url: 'http://localhost:3110'
paths:
  /api/be-even-odd:
    get:
      summary: Your GET endpoint
      tags:
        - default
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/endpoints/be-even-odd/get/SuccessResponse.yaml
      operationId: get-api-be-even-odd
      parameters:
        - schema:
            type: string
          in: query
          name: numberFromRouteHandler
          required: true
      description: 'query param の値が数字であれば even, odd の別を返す。数字でなければ NaN を返す'
components:
  schemas: {}
tags:
  - name: default
    description: 取り急ぎ
